CREATE TABLE IF NOT EXISTS profiles (id INTEGER PRIMARY KEY, phone TEXT, name TEXT, password TEXT);
CREATE TABLE IF NOT EXISTS categories (id INTEGER PRIMARY KEY, name TEXT);
CREATE TABLE IF NOT EXISTS postings (id INTEGER PRIMARY KEY, profileid INTEGER, caption TEXT, content TEXT);
CREATE TABLE IF NOT EXISTS session (id INTEGER PRIMARY KEY, profileid INTEGER, cookie TEXT, timestamp INTEGER);
