CREATE TABLE IF NOT EXISTS categories (id INTEGER PRIMARY KEY, name TEXT);
CREATE TABLE IF NOT EXISTS postings (id INTEGER PRIMARY KEY, categoryId INTEGER, cookieid INTEGER, caption TEXT, content TEXT, phonenumber TEXT, created INTEGER);
CREATE TABLE IF NOT EXISTS favorites (id INTEGER PRIMARY KEY, cookieid INTEGER, postingid INTEGER);
CREATE TABLE IF NOT EXISTS cookies (id INTEGER PRIMARY KEY, cookie TEXT);